### ISSUE TITLE
Pages can't be rearranged

### ISSUE THREAD

**Issue by maxxst** [getkirby-v2/langkit#9]
When I try to rearrange the pages they just jump back. With `Home` it works tho ...

All folders and files have the same access levels

![2017-11-26 at 22 12](https://user-images.githubusercontent.com/570654/33244434-5c7fa890-d2f7-11e7-878d-beff3d1a237a.gif)

**Comment by texnixe** [comment]
That's because the status option is set to false in the `false` in the corresponding blueprints.
